// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"firebase.google.com/go/v4"
	"github.com/google/wire"
	"github.com/rohanbojja/legalaidcamp-go/controller"
	"github.com/rohanbojja/legalaidcamp-go/repositories"
	"github.com/rohanbojja/legalaidcamp-go/service"
)

// Injectors from wire.go:

func InitializeAdminController(app *firebase.App) controller.AdminController {
	lawyerRepository := repositories.NewLawyerRepository(app)
	courtCaseRepository := repositories.NewCourtCaseRepository(app)
	adminService := service.NewAdminService(lawyerRepository, courtCaseRepository)
	authService := service.NewAuthService(app)
	adminController := controller.NewAdminController(adminService, authService, courtCaseRepository, lawyerRepository)
	return adminController
}

func InitializeLawyerController(app *firebase.App) controller.LawyerController {
	authService := service.NewAuthService(app)
	courtCaseRepository := repositories.NewCourtCaseRepository(app)
	lawyerRepository := repositories.NewLawyerRepository(app)
	lawyerService := service.NewLawyerService(lawyerRepository)
	lawyerController := controller.NewLawyerController(authService, courtCaseRepository, lawyerRepository, lawyerService)
	return lawyerController
}

func InitializeUserController(app *firebase.App) controller.UserController {
	courtCaseRepository := repositories.NewCourtCaseRepository(app)
	lawyerRepository := repositories.NewLawyerRepository(app)
	userRepository := repositories.NewUserRepository(app)
	userService := service.NewUserService(courtCaseRepository, lawyerRepository, userRepository, app)
	authService := service.NewAuthService(app)
	userController := controller.NewUserController(userService, authService)
	return userController
}

// wire.go:

var conts = wire.NewSet(controller.NewAdminController, controller.NewLawyerController, controller.NewUserController)

var repos = wire.NewSet(repositories.NewCourtCaseRepository, repositories.NewLawyerRepository, repositories.NewUserRepository)

var servs = wire.NewSet(service.NewAdminService, service.NewAuthService, service.NewLawyerService, service.NewUserService)
